global:
  scrape_interval: 15s

scrape_configs:
  # Métriques de ton application (les clics)
  - job_name: 'inptic-app'
    static_configs:
      - targets: ['app:5000']

  # Métriques de l'infrastructure via cAdvisor
  # On utilise le port 8080 car c'est le port interne au réseau Docker
  - job_name: 'containers-stats'
    static_configs:
      - targets: ['cadvisor:8080']
